---
- hosts: zabbix01
  vars:
    DIRETORIO: "/usr/share/doc/zabbix-server-mysql-{{VERSAO}}/"
    MYSQLDB: zabbix
    MYSQLUSER: zabbix
    MYSQLPASS: 1q2w3e@1q2w3e
    VERSAO: "4.2.4"
    PACOTES_ZABBIX:
     - zabbix-agent
     - zabbix-release
     - zabbix-web
     - zabbix-server-mysql
     - zabbix-get
     - zabbix-web-mysql
     - mariadb
     - mariadb-libs
     - mariadb-server
     - httpd
    PACOTES_ADICIONAIS:
     - "aide"
     - "rsyslog"
     - "openssh-server"
     - "audit"
     - "policycoreutils-python"
     - "htop"
     - "net-tools"
     - "bash-completion"
     - "bind-utils"
     - "vim"
     - "MySQL-python"
     - "libsemanage-python"
     - "git"
     - "mod_ssl"
     - "net-snmp-utils"
    SERVICOS:
     - "zabbix-server"
     - "zabbix-agent"
     - "mariadb"
     - "httpd"

  tasks:
  - name: "Instalação de repositorio da versão"
    yum: name=https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-1.el7.noarch.rpm

  - name: "Instalação de pacotes do zabbix"
    yum: name={{PACOTES_ZABBIX}} state=present

  - name: "Instalação de repositório epel-release"
    yum: name=epel-release state=present

  - name: "Instalação de repositório epel-release"
    yum: name={{PACOTES_ADICIONAIS}} state=present

  - name: "Atualização do servidor"
    yum: name="*" state=latest

  - name: "Incialização do serviço de banco de dados MYSQL"
    service: name=mariadb state=started

  - name: "Alteração de politica de SELINUX"
    selinux: policy=targeted state=permissive     

  - name: "Download do ZABIRPO"
    git: repo=https://github.com/usiusi360/zabirepo.git dest=/usr/share/zabbix/zabirepo archive=/tmp/zabirepo.zip

  - name: "Download do MYSQL-BACKUP"
    git: repo=https://github.com/maxhq/zabbix-backup.git dest=/usr/opt/zabbix-backup archive=/tmp/zabbix-backup.zip

  - name: "Copia de arquivo de configuração do zabbix agent"
    copy: src=./files/zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf

  - name: "Copia de arquivo de configuração do zabbix server"
    template: src=./files/zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf

  - name: "Copia de arquivo de configuração do MYSQL"
    copy: src=./files/my.cnf.j2 dest=/etc/my.cnf

  - name: "Copia de arquivo de configuração do script de backup"
    copy: src=./files/backup_zabbix.sh.j2 dest=/root/backup_zabbix.sh

  - name: "Criação de base de dados"
    mysql_db: name={{MYSQLDB}} state=present
    register: result

  - name: "Criação de usuário da base de dados do ZABBIX"
    mysql_user: name={{MYSQLUSER}} password="{{MYSQLPASS}}" priv='*.*:ALL,GRANT' state=present

  - name: "Deploy de SCHEMA do banco"
    mysql_db: name={{MYSQLDB}} state=import target={{DIRETORIO}}create.sql.gz
    when: result is changed

  - name: "Alteração de TIMEZONE"
    lineinfile:
      dest: /etc/php.ini
      state: present
      regexp: 'date.timezone'
      line: 'date.timezone = America/Recife'

  - name: "Desativação do firewalld"
    systemd: state=stopped enabled=no name=firewalld

  - name: "Inicialização dos serviços instalados no servidor"
    systemd: state=started daemon_reload=yes enabled=yes name={{item}}
    with_items: "{{SERVICOS}}"
